CREATE TABLE COMPRA (IDCOMPRA BIGINT PRIMARY KEY auto_increment, 
IDPOLIZA VARCHAR(10),
PLACA VARCHAR(10), 
NUMERODOCUMENTO VARCHAR(10), 
IVA NUMERIC(10,4),
IMPUESTORIQUEZA NUMERIC(10,4),
RETTENCION NUMERIC(10,4),
VALORPOLIZA NUMERIC(20,4)
);
